### ISSUE TITLE
Speedtest Data writing failed

### ISSUE THREAD

**Issue by rodewalder** [breadlysm/speedtest-to-influxdb#25]
Hi,
I get this error after starting the image:
```
speedflux_1  | 2021-08-18 12:02:35,123 [INFO] Manual server choice : ID = None
speedflux_1  | 2021-08-18 12:02:35,123 [INFO] Speedtest Successful...Writing to Influx
speedflux_1  | 2021-08-18 12:02:35,123 [INFO] Speedtest Data:
speedflux_1  |             time: 2021-08-18T12:02:35Z
speedflux_1  |             ping: 26.77ms
speedflux_1  |             download: 62.947632Mb/s
speedflux_1  |             upload: 31.390568Mb/s
....
speedflux_1  |             server location: (PLUTEX GmbH @                 Bremen)
speedflux_1  |
speedflux_1  | Process Process-8:
speedflux_1  | Traceback (most recent call last):
speedflux_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
speedflux_1  |     self.run()
speedflux_1  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
speedflux_1  |     self._target(*self._args, **self._kwargs)
speedflux_1  |   File "/app/speedflux/data.py", line 37, in speedtest
speedflux_1  |     speedflux.INFLUXDB.process_data(data_json)
speedflux_1  |   File "/app/speedflux/influx.py", line 193, in process_data
speedflux_1  |     data = self.format_data(data)
speedflux_1  |   File "/app/speedflux/influx.py", line 118, in format_data
speedflux_1  |     tags = self.tag_selection(data)
speedflux_1  |   File "/app/speedflux/influx.py", line 189, in tag_selection
speedflux_1  |     options[tag] = tag_switch[tag]
speedflux_1  | KeyError: 'None'
```
Running with a influxdb-1.8.9-1

Best Regards

**Comment by bile0026** [comment]
Looks like you need to specify the tags you want to send to influx. Either *, or list the specific tags. By default it is set to "none" which throws a key error since None is not a valid key(tag).

**Comment by nlarenti** [comment]
Same problem, how to set valid key?

**Comment by rodewalder** [comment]
I fixed it, thank for your answers
